source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '4.2.6'
gem 'pg'
gem 'active_link_to'
gem 'bootstrap-sass'
gem 'bootstrap-will_paginate'
gem 'coffee-rails'
gem 'devise'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'puma', '~> 3.4'
gem 'pundit'
gem 'sass-rails'
gem 'will_paginate'
gem 'uglifier'
gem 'turbolinks'

group :development, :test do
  gem 'byebug'
  gem 'quiet_assets'
  gem 'spring'
  gem 'web-console'
end
