source 'https://rubygems.org'

ruby '2.5.3'
gem 'rails', '~> 5.2.1'
gem 'pg'
gem 'active_link_to'
gem 'bootstrap-sass'
gem 'bootstrap-will_paginate'
gem 'coffee-rails'
gem 'devise'
gem 'jbuilder'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'puma'
gem 'pundit'
gem 'sass-rails'
gem 'turbolinks'
gem 'uglifier'
gem 'will_paginate'

group :development, :test do
  gem 'byebug'
  #gem 'quiet_assets'
  gem 'spring'
end
